# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 654b4f4525643dff01b6c09399195d34ae24454d13e76992dfc9dbb1fe08cf92903ebc5429458b48cd85c366006121e775926d0abea9c76a805a736d1de3a69f

test:
  secret_key_base: 90269fdd9357ad0d9fb96296d13656e3a48fb1491ec7eeeeaed28a2aa9c30ae1e0ede5460ee581a4167ec7cb9bc1d722b812e15281e392f8da7e86da582c9f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
